rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx-18mode
  - rbx-19mode
  - jruby

script: "bundle exec rake spec cucumber"

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/3.1.Gemfile
  - gemfiles/3.0.Gemfile
  
matrix:
  allow_failures:
    - rvm: jruby