gem 'rake'
gem 'rack',          '1.1.0'
gem 'rspec',                  :require => 'spec'
gem 'actionpack',    '<3.0.0'
gem 'activesupport', '<3.0.0'
gem 'padrino'

# group :padrino do
#   gem 'padrino', '>=0.9.14'
# end
# group :rails2 do
#   gem 'rails', '>=2.3.5'
#   gem 'rails', '<3.0.0'
# end