source :gemcutter

gem 'activesupport', '<= 2.3.8'
gem 'padrino', '= 0.9.15'
gem 'sinatra', '= 1.0.0'

group :test do
  gem 'rake'
  gem 'rspec', '< 2.0.0'
  gem 'rspec-rails', '< 2.0.0'
end

# group :padrino do
#   gem 'padrino', '>=0.9.14'
# end
# group :rails2 do
#   gem 'rails', '>=2.3.5'
#   gem 'rails', '<3.0.0'
# end