# source :rubygems

# Project requirements
gem 'view_models'
gem 'rake'
gem 'rack-flash'
gem 'thin' # or mongrel

# Component requirements
gem 'haml'

# Test requirements


# Padrino
gem 'padrino', "0.9.14"
